// <auto-generated />
namespace HappyCows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class data_anotations_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data_anotations_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201704082241529_data_anotations_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
