// <auto-generated />
namespace HappyCows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class baseentity_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(baseentity_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "201704081400021_baseentity_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
